version: "3.9"

services:

  mysqldb:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE= projet_devops_db
      - MYSQL_ROOT_PASSWORD=
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql


  app-timesheet:
    depends_on:
      - mysqldb
    image: onskh/projet-devops:1.0.0
    restart: on-failure
    ports:
      - 8082:8082
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/projet_devops_db?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "null",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true

volumes:
  db: